### ISSUE TITLE
firestore initialization required?

### ISSUE THREAD

**Issue by petecarapetyan** [CaptainCodeman/rdx-demo#2]
When I log in using the demo - works but also getting this console log. Have never used firestore before, is there an initialization script I'm supposed to run first?

`errors.ts:101 Uncaught (in promise) FirebaseError: Analytics: "measurementId" field is empty in Firebase config. Firebase Analytics requires this field to contain a valid measurement ID. (analytics/no-ga-id).
    at Ze (https://www.gstatic.com/firebasejs/7.13.2/firebase-analytics.js:1:24542)
    at v.INTERNAL.registerComponent.g.setServiceProps.settings [as instanceFactory] (https://www.gstatic.com/firebasejs/7.13.2/firebase-analytics.js:1:26172)
    at S.getOrInitializeService (https://www.gstatic.com/firebasejs/7.13.2/firebase-app.js:1:8363)
    at S.getImmediate (https://www.gstatic.com/firebasejs/7.13.2/firebase-app.js:1:6886)
    at q._getService (https://www.gstatic.com/firebasejs/7.13.2/firebase-app.js:1:13982)
    at q.c.<computed> [as analytics] (https://www.gstatic.com/firebasejs/7.13.2/firebase-app.js:1:17401)
    at https://werradith.web.app/scripts/app.js:1:22794`

**Comment by djlauk** [comment]
In your firebase project, you probably haven't enabled the use of Google Analytics.
So your firebase project config does not contain a config field `measurementId`.

Temporary workaround:
If you just comment out [line 46 in `src/state/firebase/loader.ts`](https://github.com/CaptainCodeman/rdx-demo/blob/master/src/state/firebase/loader.ts#L46) this will go away.

Better solution (IMHO):
Only load GA, if measurementId is configured.

@CaptainCodeman What do you think? (I'm happy to provide a PR.)

**Comment by CaptainCodeman** [comment]
Yes, much of the demo code was extracted from another project, but then I switched the config and probably didn't complete all the config setup - it would make sense to just remove analytics / performance modules.
